import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Navigation from '../components/Navigation';
import Projects from '../components/Projects';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.layout}>
      <Head>
        <title>Full-Stack Software Engineer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat&display=swap"
          rel="stylesheet"
        />

        <link rel="manifest" href="/manifest.json" />
      </Head>
      <Navigation />
      <Header />
      <main className={styles.main}>
        <Projects />
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  );
}
